// automaticly generated by wsjcpp:v0.0.1

#include "__data_html_index_html_path92beac.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_html_index_html_path92beac)

const std::string &RES___data_html_index_html_path92beac::getFilename() const {
    static const std::string s = "./data/html/index.html";
    return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_html_index_html_path92beac::getPackAs() const {
    static const std::string s = "binary";
    return s;
}
// ---------------------------------------------------------------------

int RES___data_html_index_html_path92beac::getBufferSize() const {
    return 57;
}

// ---------------------------------------------------------------------

const char *RES___data_html_index_html_path92beac::getBuffer() const {
    static const unsigned char b[57] = {
        0x3c, 0x68, 0x74, 0x6d, 0x6c, 0x3e, 0x0a, 0x3c, 0x68, 0x65, 0x61, 0x64, 0x3e, 0x0a, 0x3c, 0x2f, 
        0x68, 0x65, 0x61, 0x64, 0x3e, 0x0a, 0x3c, 0x62, 0x6f, 0x64, 0x79, 0x3e, 0x0a, 0x48, 0x65, 0x6c, 
        0x6c, 0x6f, 0x20, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x21, 0x0a, 0x3c, 0x2f, 0x62, 0x6f, 0x64, 0x79, 
        0x3e, 0x0a, 0x3c, 0x2f, 0x68, 0x74, 0x6d, 0x6c, 0x3e
    };
    return (const char*)b;
} //::buffer()


