// automaticly generated by wsjcpp:v0.0.1

#include <wsjcpp_core.h>

class RES___data_html_admin_index_html_path1c7bf8 : public WsjcppResourceFile { 
    public:
        virtual const std::string &getFilename() const override;
        virtual const std::string &getPackAs() const override;
        virtual int getBufferSize() const override;
        virtual const char *getBuffer() const override;
};


