// automatically generated by wsjcpp:v0.0.1

#include "__data_html_admin_index_html_path5f17ec.h"

REGISTRY_WSJCPP_RESOURCE_FILE(RES___data_html_admin_index_html_path5f17ec)

const std::string &RES___data_html_admin_index_html_path5f17ec::getFilename() const {
  static const std::string s = "./data/html/admin/index.html";
  return s;
}
// ---------------------------------------------------------------------

const std::string &RES___data_html_admin_index_html_path5f17ec::getPackAs() const {
  static const std::string s = "binary";
  return s;
}
// ---------------------------------------------------------------------

int RES___data_html_admin_index_html_path5f17ec::getBufferSize() const {
  return 50;
}

// ---------------------------------------------------------------------

const char *RES___data_html_admin_index_html_path5f17ec::getBuffer() const {
  static const unsigned char b[50] = {
    0x3c, 0x68, 0x74, 0x6d, 0x6c, 0x3e, 0x0a, 0x3c, 0x68, 0x65, 0x61, 0x64, 0x3e, 0x0a, 0x3c, 0x2f,
    0x68, 0x65, 0x61, 0x64, 0x3e, 0x0a, 0x3c, 0x62, 0x6f, 0x64, 0x79, 0x3e, 0x0a, 0x41, 0x64, 0x6d,
    0x69, 0x6e, 0x0a, 0x3c, 0x2f, 0x62, 0x6f, 0x64, 0x79, 0x3e, 0x0a, 0x3c, 0x2f, 0x68, 0x74, 0x6d,
    0x6c, 0x3e
  };
  return (const char *)b;
} //::getBuffer()


